// This file is automatically generated from CMake
#ifndef UTILS_PATHS_H
#define UTILS_PATHS_H

#define VRC_ROOT_PATH "/home/eric/src/vrc-golem/dart-atlas/"
#define VRC_DATA_PATH "/home/eric/src/vrc-golem/dart-atlas/data/"

#endif // ifndef UTILS_PATHS_H
